apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  containers:
    - name: consumer
      image: yenreh/kafka-consumer:latest
      env:
        - name: KAFKA_BROKER
          value: kafka-broker-1:9092
