# Zookeeper Pod
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:latest
      ports:
        - containerPort: 2181
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"

---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

---
# Kafka Pod
apiVersion: v1
kind: Pod
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker
spec:
  containers:
    - name: kafka
      image: confluentinc/cp-kafka:latest
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker-1:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker
