apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  containers:
    - name: producer
      image: yenreh/kafka-producer:latest
      env:
        - name: KAFKA_BROKER
          value: kafka-broker-1:9092

